//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::{entity::prelude::*, ActiveValue::Set};

use crate::database::entity::DB_SONYFLAKE;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "album_uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created: DateTimeWithTimeZone,
    pub upload_id: String,
    pub album_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Albums,
    #[sea_orm(
        belongs_to = "super::uploads::Entity",
        from = "Column::UploadId",
        to = "super::uploads::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Uploads,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Albums.def()
    }
}

impl Related<super::uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Uploads.def()
    }
}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(DB_SONYFLAKE.next_id().unwrap().to_string()),
            ..ActiveModelTrait::default()
        }
    }
}
