//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use crate::database::sonyflake::Sonyflake;

pub mod prelude;

pub mod applications;
pub mod files;
pub mod sea_orm_active_enums;
pub mod users;
pub mod verifications;

lazy_static! {
    pub static ref DB_SONYFLAKE: Sonyflake =
        Sonyflake::new(0, None).expect("There was a problem creating the Sonyflake worker");
}
