//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "theme_color")]
pub enum ThemeColor {
    #[sea_orm(string_value = "blue")]
    Blue,
    #[sea_orm(string_value = "cyan")]
    Cyan,
    #[sea_orm(string_value = "gray")]
    Gray,
    #[sea_orm(string_value = "green")]
    Green,
    #[sea_orm(string_value = "orange")]
    Orange,
    #[sea_orm(string_value = "pink")]
    Pink,
    #[sea_orm(string_value = "purple")]
    Purple,
    #[sea_orm(string_value = "red")]
    Red,
    #[sea_orm(string_value = "teal")]
    Teal,
    #[sea_orm(string_value = "yellow")]
    Yellow,
}
#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "user")]
    User,
}
