[package]
name = "kawaii"
version = "0.1.0"
authors = ["Riku <riku@kawaii.sh>"]
edition = "2018"

[dependencies]
sqlx = { version = "0.4.2", features = [ "runtime-async-std-native-tls", "postgres" ] }
serde = "1.0.123"
serde_json = { version = "1.0.59", features = [ "preserve_order" ] }
dotenv = "0.15.0"
actix-web = "3"
rust-argon2 = "0.8.3"
rusoto_s3 = "0.46.0"
rusoto_core = "0.46.0"
infer = "0.3.4"
rand = "0.8.3"
jwt = "0.12.0"
hmac = "0.9"
sha2 = "0.9"
futures = "0.3.12"
time = "0.2.25"
chrono = "0.4"
macro_rules_attribute = "0.0.1"