[package]
name = "anolis"
version = "0.1.0"
authors = ["Riku <riku@kawaii.sh>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
sqlx = { version = "0.5.5", features = [ "runtime-async-std-native-tls", "postgres" ] }
serde = "1.0.123"
serde_json = { version = "1.0.59", features = [ "preserve_order" ] }
jsonwebtoken = { git = "https://github.com/Riku32/jsonwebtoken" }
dotenv = "0.15.0"
actix-web = "3.3.2"
rust-argon2 = "0.8.3"
rusoto_s3 = "0.43.0"
rusoto_core = "0.43.0"
infer = "0.3.4"
rand = "0.8.3"
futures = "0.3.12"
time = "0.2.25"
chrono = "0.4"
async-trait = "0.1.42"
env_logger = "0.8.3"
colored = "2"