[package]
name = "kawaii"
version = "0.1.0"
authors = ["Riku <riku@kawaii.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.4.2", features = [ "runtime-async-std-native-tls", "postgres" ] }
serde = "1.0.123"
serde_json = "1.0.59"
dotenv = "0.15.0"
actix-web = "3"
rust-argon2 = "0.8.3"
rusoto_s3 = "0.46.0"
rusoto_core = "0.46.0"
infer = "0.3.4"
rand = "0.8.3"