version: "3.9"
services:
  backpack_api:
    build: ./
    env_file: .env
    environment:
      PORT: 3000
      LOCAL_PATH: /uploads
    volumes:
      # This will only be used if using local storage
      - ${LOCAL_PATH}:/uploads
  backpack_frontend:
    build: ./frontend
    env_file: .env
    depends_on:
      - backpack_api
    environment:
      PORT: 3000
      INTERNAL_API_URL: "http://backpack_api:3000"
  proxy:
    build: ./nginx
    ports:
      - ${PORT}:80
    env_file: .env
    depends_on:
      - backpack_api
      - backpack_client