version: "3.9"
services:
  backpack_api:
    build: ./
    env_file: .env
    environment:
      PORT: 3000
      LOCAL_PATH: /uploads
    volumes:
      # This will only be used if using local storage
      - ${LOCAL_PATH}:/uploads
  backpack_client:
    build: ./client
    env_file: .env
    depends_on:
      - backpack_api
    environment:
      PORT: 3000
      INTERNAL_API_URL: "http://backpack_api:3000"
  proxy:
    image: nginx
    ports:
      - ${PORT}:80
    env_file: .env
    environment:
      # This should be "on" if serving files through the API
      # This is always the case if LOCAL_SERVE is true
      # If serving files seperately or using S3 this should be "off"
      PROXY_FILES: "on"
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - backpack_api
      - backpack_client