use sea_orm::prelude::DateTimeUtc;
use serde::{Deserialize, Serialize};
use utoipa::Component;

use crate::database::entity::applications;

#[derive(Serialize, Component)]
#[serde(rename_all = "camelCase")]
pub struct ApplicationData {
    pub name: String,
    pub id: String,

    /// Last time the application was used for a request
    #[component(value_type = f64, read_only)]
    pub last_accessed: DateTimeUtc,

    #[serde(skip_serializing)]
    #[component(read_only)]
    pub user_id: String,

    /// Only sent when the token is originally created
    #[serde(skip_serializing_if = "Option::is_none")]
    #[component(read_only)]
    pub token: Option<String>,
}

impl From<applications::Model> for ApplicationData {
    fn from(application: applications::Model) -> Self {
        Self {
            id: application.id,
            name: application.name,
            user_id: application.user_id,
            last_accessed: application.last_accessed,
            // Token is generated by JWT with parameters, not stored in DB
            token: None,
        }
    }
}

/// Token data response
#[derive(Serialize, Component)]
pub struct TokenResponse {
    pub token: String,
}

/// Application create request
#[derive(Deserialize, Component)]
pub struct ApplicationCreate {
    pub name: String,
}
